version: "3"

services:
  discord-musicbot:
    build: .
    image: zunderene/music-bot:master
    container_name: discord-musicbot
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    environment:
      Prefix : '/'
      Token: MTA2NDIwNDk3ODE2NTY1MzUyNA.Gu0zYk.Lfm6pAbr2QbJ11CCS4oYxn4LiDvcdfCksBH3rE
      Discord_ClientID:  "1064204978165653524"
      Discord_ClientSecret: hP_X3IafUDJVt4lnf6-clbPMG2mbRA6z
      NODE_HOST: "lavalink"
      NODE_ID: "lavamusic-lavalink"
      NODE_PORT: "2333"
      NODE_PASSWORD: "youshallnotpass"
      NODE_SECURE: "false"
    links:
      - lavalink

  lavalink:
    image: fredboat/lavalink:dev
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    environment:
      SERVER_PORT: 2333
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
      LAVALINK_SERVER_SOURCES_YOUTUBE: "true"
      LAVALINK_SERVER_SOURCES_BANDCAMP: "true"
      LAVALINK_SERVER_SOURCES_SOUNDCLOUD: "true"
      LAVALINK_SERVER_SOURCES_TWITCH: "true"
      LAVALINK_SERVER_SOURCES_VIMEO: "true"
      LAVALINK_SERVER_SOURCES_HTTP: "true"
      LAVALINK_SERVER_SOURCES_LOCAL: "false"
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATIONS_MS: 5000
      LAVALINK_SERVER_TRACK_STRUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 6
      LAVALINK_SERVER_PLAYER_UPDATE_INTERVAL: 5
      LAVALINK_SERVER_YOUTUBE_SEARCH_ENABLED: "true"
      LAVALINK_SERVER_SOUNDCLOUD_SEARCH_ENABLED: "true"
      #LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL:
      #LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD:
      LAVALINK_SERVER_SENTRY_DSN: ""

networks:
  lavalink-net:


  
